<?
$title = "OceanCurrent - Acknowledgements";
ini_set('include_path', './' . PATH_SEPARATOR . '../' . PATH_SEPARATOR . ini_get('include_path'));
include_once("include/header.php");
?>

<div class="row">
    <div class="col-md-4">
        <h3>The <em>OceanCurrent</em> part of the IMOS website and the processing systems that update the graphics
            content have been developed over the years by Dr David Griffin and his colleagues at the CSIRO Division of
            Marine and
            Atmospheric Research, as part of a sequence of projects.</h3>
    </div>
    <div class="col-md-4">
        <a href="http://www.marine.csiro.au/~griffin/WACD/index.htm">
            WA ocean movies, 1993-2000
            <img src="http://www.marine.csiro.au/~griffin/WACD/cdcover/WAcd.jpg">
        </a>
    </div>
    <div class="col-md-4">
        <a href="http://www.marine.csiro.au/~griffin/SEF/index.htm">
            South-East Fishery ocean movie
            <img src="http://www.marine.csiro.au/~griffin/SEF/gifs/SEFcd.jpg">
        </a>
    </div>
</div>
<div class="row">
    <p>
        Initial work on algorithms for deriving geostrophic currents from multi-mission altimetry and tidegauges was
        performed with support from the Fisheries Research and Development Corporation in collaboration with John
        Wilkin.
        Real-time implementation of geostrophic current estimation was led by Scott Condie and Madeleine Cahill with
        support
        from the Australian Maritime Safety Authority.
    </p>
    <p>
        Methods for processing AVHRR data and producing and visualising high-resolution composite SST images were
        initially
        developed by Paul Tildesley, Chris Rathbone, Kim Badcock and John Parslow. The CSIRO method for precise
        geo-location
        of SST imagery was developed by Steve Clift. The process for merging AVHRR data received from several
        groundstations
        was developed by Edward King at the CSIRO Earth Observation Centre. The Australian National Marine Data Group of
        the
        National Oceans Office supported CSIRO to put the then 10-year long archive of Australasian SST imagery in the
        public domain through the <a href=ten_years_of_SST/>'Ten Years of SST' project</a> (the data set is now, in
        2011,
        nearly 20 years long and available through EMII). The SST imagery added to the website shifted in late 2011 from
        using the products of the CSIRO Hobart system, to those generated by George Paltoglou and Helen Beggs at the
        Bureau
        of Meteorology as a contribution to the <a href=http://imos.org.au/srs.html> Satellite Remote Sensing
            Facility</a>
        led by Edward King.
    </p>
    <p>
        The CSIRO-BoM-RAN Bluelink project supported the further development of the site from 2002 to 2006, during which
        period Ken Ridgway and Jeff Dunn developed the 'synTS' method for estimating subsurface temperature from the
        joint
        use of altimetry and SST imagery. Madeleine Cahill and Jim Mansbridge maintained and improved the altimetry
        processing, while Ken Suber and Peter Turner assisted with the production of kml files so the imagery could be
        viewed using Google Earth.
        We are especially grateful to those agencies and individuals who provide the <a href="sourcedata/"> source
            data </a>,
        without which this service would not be possible.
    </p>
</div>
<?
include('include/footer.php');
?>
